# default (local)
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3306/example?characterEncoding=utf8&autoReconnect=true
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://spring-vpc-db.ciamiexdzz7r.ap-northeast-2.rds.amazonaws.com:3306/example?characterEncoding=utf8&autoReconnect=true
    username: admin
    password: skfTlrkdPQjdy777.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug